version: '3.1'
services:
  javaapplication:
    image: swaroopchalla/java-web-app:TAG
    restart: always
    ports:
    - 9000:8080
    networks:
    - mavenwebapp
    deploy:
     replicas: 4
     update_config:
      parallelism: 1
      delay: 30s
     placement:
      constraints:
      - "node.role==worker"
networks:
  mavenwebapp:
